from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model import Model
from .. import util


class AasSubmodelElements(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ANNOTATEDRELATIONSHIPELEMENT = 'AnnotatedRelationshipElement'
    BASICEVENTELEMENT = 'BasicEventElement'
    BLOB = 'Blob'
    CAPABILITY = 'Capability'
    DATAELEMENT = 'DataElement'
    ENTITY = 'Entity'
    EVENTELEMENT = 'EventElement'
    FILE = 'File'
    MULTILANGUAGEPROPERTY = 'MultiLanguageProperty'
    OPERATION = 'Operation'
    PROPERTY = 'Property'
    RANGE = 'Range'
    REFERENCEELEMENT = 'ReferenceElement'
    RELATIONSHIPELEMENT = 'RelationshipElement'
    SUBMODELELEMENT = 'SubmodelElement'
    SUBMODELELEMENTCOLLECTION = 'SubmodelElementCollection'
    SUBMODELELEMENTLIST = 'SubmodelElementList'
    def __init__(self):  # noqa: E501
        """AasSubmodelElements - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AasSubmodelElements':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AasSubmodelElements of this AasSubmodelElements.  # noqa: E501
        :rtype: AasSubmodelElements
        """
        return util.deserialize_model(dikt, cls)
