from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model import Model
from .. import util


class AssetKind(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    INSTANCE = 'Instance'
    NOTAPPLICABLE = 'NotApplicable'
    TYPE = 'Type'
    def __init__(self):  # noqa: E501
        """AssetKind - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AssetKind':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssetKind of this AssetKind.  # noqa: E501
        :rtype: AssetKind
        """
        return util.deserialize_model(dikt, cls)
