from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model import Model
from .. import util


class ExecutionState(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    INITIATED = 'Initiated'
    RUNNING = 'Running'
    COMPLETED = 'Completed'
    CANCELED = 'Canceled'
    FAILED = 'Failed'
    TIMEOUT = 'Timeout'
    def __init__(self):  # noqa: E501
        """ExecutionState - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ExecutionState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExecutionState of this ExecutionState.  # noqa: E501
        :rtype: ExecutionState
        """
        return util.deserialize_model(dikt, cls)
