from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model import Model
from .. import util


class KeyTypes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ANNOTATEDRELATIONSHIPELEMENT = 'AnnotatedRelationshipElement'
    ASSETADMINISTRATIONSHELL = 'AssetAdministrationShell'
    BASICEVENTELEMENT = 'BasicEventElement'
    BLOB = 'Blob'
    CAPABILITY = 'Capability'
    CONCEPTDESCRIPTION = 'ConceptDescription'
    DATAELEMENT = 'DataElement'
    ENTITY = 'Entity'
    EVENTELEMENT = 'EventElement'
    FILE = 'File'
    FRAGMENTREFERENCE = 'FragmentReference'
    GLOBALREFERENCE = 'GlobalReference'
    IDENTIFIABLE = 'Identifiable'
    MULTILANGUAGEPROPERTY = 'MultiLanguageProperty'
    OPERATION = 'Operation'
    PROPERTY = 'Property'
    RANGE = 'Range'
    REFERABLE = 'Referable'
    REFERENCEELEMENT = 'ReferenceElement'
    RELATIONSHIPELEMENT = 'RelationshipElement'
    SUBMODEL = 'Submodel'
    SUBMODELELEMENT = 'SubmodelElement'
    SUBMODELELEMENTCOLLECTION = 'SubmodelElementCollection'
    SUBMODELELEMENTLIST = 'SubmodelElementList'
    def __init__(self):  # noqa: E501
        """KeyTypes - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'KeyTypes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The KeyTypes of this KeyTypes.  # noqa: E501
        :rtype: KeyTypes
        """
        return util.deserialize_model(dikt, cls)
