from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model import Model
from ..models.aas_submodel_elements import AasSubmodelElements
from ..models.data_type_def_xsd import DataTypeDefXsd
from ..models.embedded_data_specification import EmbeddedDataSpecification
from ..models.extension import Extension
from ..models.lang_string_name_type import LangStringNameType
from ..models.lang_string_text_type import LangStringTextType
from ..models.qualifier import Qualifier
from ..models.reference import Reference
from ..models.submodel_element_choice import SubmodelElementChoice
import re
from .. import util

from ..models.aas_submodel_elements import AasSubmodelElements  # noqa: E501
from ..models.data_type_def_xsd import DataTypeDefXsd  # noqa: E501
from ..models.embedded_data_specification import EmbeddedDataSpecification  # noqa: E501
from ..models.extension import Extension  # noqa: E501
from ..models.lang_string_name_type import LangStringNameType  # noqa: E501
from ..models.lang_string_text_type import LangStringTextType  # noqa: E501
from ..models.qualifier import Qualifier  # noqa: E501
from ..models.reference import Reference  # noqa: E501
from ..models.submodel_element_choice import SubmodelElementChoice  # noqa: E501
import re  # noqa: E501

class SubmodelElementList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, extensions=None, category=None, id_short=None, display_name=None, description=None, model_type=None, semantic_id=None, supplemental_semantic_ids=None, qualifiers=None, embedded_data_specifications=None, order_relevant=None, semantic_id_list_element=None, type_value_list_element=None, value_type_list_element=None, value=None):  # noqa: E501
        """SubmodelElementList - a model defined in OpenAPI

        :param extensions: The extensions of this SubmodelElementList.  # noqa: E501
        :type extensions: List[Extension]
        :param category: The category of this SubmodelElementList.  # noqa: E501
        :type category: str
        :param id_short: The id_short of this SubmodelElementList.  # noqa: E501
        :type id_short: object
        :param display_name: The display_name of this SubmodelElementList.  # noqa: E501
        :type display_name: List[LangStringNameType]
        :param description: The description of this SubmodelElementList.  # noqa: E501
        :type description: List[LangStringTextType]
        :param model_type: The model_type of this SubmodelElementList.  # noqa: E501
        :type model_type: str
        :param semantic_id: The semantic_id of this SubmodelElementList.  # noqa: E501
        :type semantic_id: Reference
        :param supplemental_semantic_ids: The supplemental_semantic_ids of this SubmodelElementList.  # noqa: E501
        :type supplemental_semantic_ids: List[Reference]
        :param qualifiers: The qualifiers of this SubmodelElementList.  # noqa: E501
        :type qualifiers: List[Qualifier]
        :param embedded_data_specifications: The embedded_data_specifications of this SubmodelElementList.  # noqa: E501
        :type embedded_data_specifications: List[EmbeddedDataSpecification]
        :param order_relevant: The order_relevant of this SubmodelElementList.  # noqa: E501
        :type order_relevant: bool
        :param semantic_id_list_element: The semantic_id_list_element of this SubmodelElementList.  # noqa: E501
        :type semantic_id_list_element: Reference
        :param type_value_list_element: The type_value_list_element of this SubmodelElementList.  # noqa: E501
        :type type_value_list_element: AasSubmodelElements
        :param value_type_list_element: The value_type_list_element of this SubmodelElementList.  # noqa: E501
        :type value_type_list_element: DataTypeDefXsd
        :param value: The value of this SubmodelElementList.  # noqa: E501
        :type value: List[SubmodelElementChoice]
        """
        self.openapi_types = {
            'extensions': List[Extension],
            'category': str,
            'id_short': object,
            'display_name': List[LangStringNameType],
            'description': List[LangStringTextType],
            'model_type': str,
            'semantic_id': Reference,
            'supplemental_semantic_ids': List[Reference],
            'qualifiers': List[Qualifier],
            'embedded_data_specifications': List[EmbeddedDataSpecification],
            'order_relevant': bool,
            'semantic_id_list_element': Reference,
            'type_value_list_element': AasSubmodelElements,
            'value_type_list_element': DataTypeDefXsd,
            'value': List[SubmodelElementChoice]
        }

        self.attribute_map = {
            'extensions': 'extensions',
            'category': 'category',
            'id_short': 'idShort',
            'display_name': 'displayName',
            'description': 'description',
            'model_type': 'modelType',
            'semantic_id': 'semanticId',
            'supplemental_semantic_ids': 'supplementalSemanticIds',
            'qualifiers': 'qualifiers',
            'embedded_data_specifications': 'embeddedDataSpecifications',
            'order_relevant': 'orderRelevant',
            'semantic_id_list_element': 'semanticIdListElement',
            'type_value_list_element': 'typeValueListElement',
            'value_type_list_element': 'valueTypeListElement',
            'value': 'value'
        }

        self._extensions = extensions
        self._category = category
        self._id_short = id_short
        self._display_name = display_name
        self._description = description
        self._model_type = model_type
        self._semantic_id = semantic_id
        self._supplemental_semantic_ids = supplemental_semantic_ids
        self._qualifiers = qualifiers
        self._embedded_data_specifications = embedded_data_specifications
        self._order_relevant = order_relevant
        self._semantic_id_list_element = semantic_id_list_element
        self._type_value_list_element = type_value_list_element
        self._value_type_list_element = value_type_list_element
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'SubmodelElementList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubmodelElementList of this SubmodelElementList.  # noqa: E501
        :rtype: SubmodelElementList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def extensions(self) -> List[Extension]:
        """Gets the extensions of this SubmodelElementList.


        :return: The extensions of this SubmodelElementList.
        :rtype: List[Extension]
        """
        return self._extensions

    @extensions.setter
    def extensions(self, extensions: List[Extension]):
        """Sets the extensions of this SubmodelElementList.


        :param extensions: The extensions of this SubmodelElementList.
        :type extensions: List[Extension]
        """
        if extensions is not None and len(extensions) < 1:
            raise ValueError("Invalid value for `extensions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._extensions = extensions

    @property
    def category(self) -> str:
        """Gets the category of this SubmodelElementList.


        :return: The category of this SubmodelElementList.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this SubmodelElementList.


        :param category: The category of this SubmodelElementList.
        :type category: str
        """
        if category is not None and len(category) > 128:
            raise ValueError("Invalid value for `category`, length must be less than or equal to `128`")  # noqa: E501
        if category is not None and len(category) < 1:
            raise ValueError("Invalid value for `category`, length must be greater than or equal to `1`")  # noqa: E501
        if category is not None and not re.search(r'^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$', category):  # noqa: E501
            raise ValueError("Invalid value for `category`, must be a follow pattern or equal to `/^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$/`")  # noqa: E501

        self._category = category

    @property
    def id_short(self) -> object:
        """Gets the id_short of this SubmodelElementList.


        :return: The id_short of this SubmodelElementList.
        :rtype: object
        """
        return self._id_short

    @id_short.setter
    def id_short(self, id_short: object):
        """Sets the id_short of this SubmodelElementList.


        :param id_short: The id_short of this SubmodelElementList.
        :type id_short: object
        """

        self._id_short = id_short

    @property
    def display_name(self) -> List[LangStringNameType]:
        """Gets the display_name of this SubmodelElementList.


        :return: The display_name of this SubmodelElementList.
        :rtype: List[LangStringNameType]
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: List[LangStringNameType]):
        """Sets the display_name of this SubmodelElementList.


        :param display_name: The display_name of this SubmodelElementList.
        :type display_name: List[LangStringNameType]
        """
        if display_name is not None and len(display_name) < 1:
            raise ValueError("Invalid value for `display_name`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self) -> List[LangStringTextType]:
        """Gets the description of this SubmodelElementList.


        :return: The description of this SubmodelElementList.
        :rtype: List[LangStringTextType]
        """
        return self._description

    @description.setter
    def description(self, description: List[LangStringTextType]):
        """Sets the description of this SubmodelElementList.


        :param description: The description of this SubmodelElementList.
        :type description: List[LangStringTextType]
        """
        if description is not None and len(description) < 1:
            raise ValueError("Invalid value for `description`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def model_type(self) -> str:
        """Gets the model_type of this SubmodelElementList.


        :return: The model_type of this SubmodelElementList.
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type: str):
        """Sets the model_type of this SubmodelElementList.


        :param model_type: The model_type of this SubmodelElementList.
        :type model_type: str
        """
        if model_type is None:
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501
        if model_type is not None and not re.search(r'SubmodelElementList', model_type):  # noqa: E501
            raise ValueError("Invalid value for `model_type`, must be a follow pattern or equal to `/SubmodelElementList/`")  # noqa: E501

        self._model_type = model_type

    @property
    def semantic_id(self) -> Reference:
        """Gets the semantic_id of this SubmodelElementList.


        :return: The semantic_id of this SubmodelElementList.
        :rtype: Reference
        """
        return self._semantic_id

    @semantic_id.setter
    def semantic_id(self, semantic_id: Reference):
        """Sets the semantic_id of this SubmodelElementList.


        :param semantic_id: The semantic_id of this SubmodelElementList.
        :type semantic_id: Reference
        """

        self._semantic_id = semantic_id

    @property
    def supplemental_semantic_ids(self) -> List[Reference]:
        """Gets the supplemental_semantic_ids of this SubmodelElementList.


        :return: The supplemental_semantic_ids of this SubmodelElementList.
        :rtype: List[Reference]
        """
        return self._supplemental_semantic_ids

    @supplemental_semantic_ids.setter
    def supplemental_semantic_ids(self, supplemental_semantic_ids: List[Reference]):
        """Sets the supplemental_semantic_ids of this SubmodelElementList.


        :param supplemental_semantic_ids: The supplemental_semantic_ids of this SubmodelElementList.
        :type supplemental_semantic_ids: List[Reference]
        """
        if supplemental_semantic_ids is not None and len(supplemental_semantic_ids) < 1:
            raise ValueError("Invalid value for `supplemental_semantic_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._supplemental_semantic_ids = supplemental_semantic_ids

    @property
    def qualifiers(self) -> List[Qualifier]:
        """Gets the qualifiers of this SubmodelElementList.


        :return: The qualifiers of this SubmodelElementList.
        :rtype: List[Qualifier]
        """
        return self._qualifiers

    @qualifiers.setter
    def qualifiers(self, qualifiers: List[Qualifier]):
        """Sets the qualifiers of this SubmodelElementList.


        :param qualifiers: The qualifiers of this SubmodelElementList.
        :type qualifiers: List[Qualifier]
        """
        if qualifiers is not None and len(qualifiers) < 1:
            raise ValueError("Invalid value for `qualifiers`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._qualifiers = qualifiers

    @property
    def embedded_data_specifications(self) -> List[EmbeddedDataSpecification]:
        """Gets the embedded_data_specifications of this SubmodelElementList.


        :return: The embedded_data_specifications of this SubmodelElementList.
        :rtype: List[EmbeddedDataSpecification]
        """
        return self._embedded_data_specifications

    @embedded_data_specifications.setter
    def embedded_data_specifications(self, embedded_data_specifications: List[EmbeddedDataSpecification]):
        """Sets the embedded_data_specifications of this SubmodelElementList.


        :param embedded_data_specifications: The embedded_data_specifications of this SubmodelElementList.
        :type embedded_data_specifications: List[EmbeddedDataSpecification]
        """
        if embedded_data_specifications is not None and len(embedded_data_specifications) < 1:
            raise ValueError("Invalid value for `embedded_data_specifications`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._embedded_data_specifications = embedded_data_specifications

    @property
    def order_relevant(self) -> bool:
        """Gets the order_relevant of this SubmodelElementList.


        :return: The order_relevant of this SubmodelElementList.
        :rtype: bool
        """
        return self._order_relevant

    @order_relevant.setter
    def order_relevant(self, order_relevant: bool):
        """Sets the order_relevant of this SubmodelElementList.


        :param order_relevant: The order_relevant of this SubmodelElementList.
        :type order_relevant: bool
        """

        self._order_relevant = order_relevant

    @property
    def semantic_id_list_element(self) -> Reference:
        """Gets the semantic_id_list_element of this SubmodelElementList.


        :return: The semantic_id_list_element of this SubmodelElementList.
        :rtype: Reference
        """
        return self._semantic_id_list_element

    @semantic_id_list_element.setter
    def semantic_id_list_element(self, semantic_id_list_element: Reference):
        """Sets the semantic_id_list_element of this SubmodelElementList.


        :param semantic_id_list_element: The semantic_id_list_element of this SubmodelElementList.
        :type semantic_id_list_element: Reference
        """

        self._semantic_id_list_element = semantic_id_list_element

    @property
    def type_value_list_element(self) -> AasSubmodelElements:
        """Gets the type_value_list_element of this SubmodelElementList.


        :return: The type_value_list_element of this SubmodelElementList.
        :rtype: AasSubmodelElements
        """
        return self._type_value_list_element

    @type_value_list_element.setter
    def type_value_list_element(self, type_value_list_element: AasSubmodelElements):
        """Sets the type_value_list_element of this SubmodelElementList.


        :param type_value_list_element: The type_value_list_element of this SubmodelElementList.
        :type type_value_list_element: AasSubmodelElements
        """
        if type_value_list_element is None:
            raise ValueError("Invalid value for `type_value_list_element`, must not be `None`")  # noqa: E501

        self._type_value_list_element = type_value_list_element

    @property
    def value_type_list_element(self) -> DataTypeDefXsd:
        """Gets the value_type_list_element of this SubmodelElementList.


        :return: The value_type_list_element of this SubmodelElementList.
        :rtype: DataTypeDefXsd
        """
        return self._value_type_list_element

    @value_type_list_element.setter
    def value_type_list_element(self, value_type_list_element: DataTypeDefXsd):
        """Sets the value_type_list_element of this SubmodelElementList.


        :param value_type_list_element: The value_type_list_element of this SubmodelElementList.
        :type value_type_list_element: DataTypeDefXsd
        """

        self._value_type_list_element = value_type_list_element

    @property
    def value(self) -> List[SubmodelElementChoice]:
        """Gets the value of this SubmodelElementList.


        :return: The value of this SubmodelElementList.
        :rtype: List[SubmodelElementChoice]
        """
        return self._value

    @value.setter
    def value(self, value: List[SubmodelElementChoice]):
        """Sets the value of this SubmodelElementList.


        :param value: The value of this SubmodelElementList.
        :type value: List[SubmodelElementChoice]
        """
        if value is not None and len(value) < 1:
            raise ValueError("Invalid value for `value`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._value = value
