from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model import Model
from ..models.aas_submodel_elements import AasSubmodelElements
from ..models.annotated_relationship_element import AnnotatedRelationshipElement
from ..models.basic_event_element import BasicEventElement
from ..models.blob import Blob
from ..models.capability import Capability
from ..models.data_element_choice import DataElementChoice
from ..models.data_type_def_xsd import DataTypeDefXsd
from ..models.direction import Direction
from ..models.embedded_data_specification import EmbeddedDataSpecification
from ..models.entity import Entity
from ..models.entity_type import EntityType
from ..models.extension import Extension
from ..models.file import File
from ..models.lang_string_name_type import LangStringNameType
from ..models.lang_string_text_type import LangStringTextType
from ..models.model_property import ModelProperty
from ..models.multi_language_property import MultiLanguageProperty
from ..models.operation import Operation
from ..models.operation_variable import OperationVariable
from ..models.qualifier import Qualifier
from ..models.range import Range
from ..models.reference import Reference
from ..models.reference_element import ReferenceElement
from ..models.relationship_element import RelationshipElement
from ..models.specific_asset_id import SpecificAssetId
from ..models.state_of_event import StateOfEvent
from ..models.submodel_element_collection import SubmodelElementCollection
from ..models.submodel_element_list import SubmodelElementList
import re
from .. import util

from ..models.aas_submodel_elements import AasSubmodelElements  # noqa: E501
from ..models.annotated_relationship_element import AnnotatedRelationshipElement  # noqa: E501
from ..models.basic_event_element import BasicEventElement  # noqa: E501
from ..models.blob import Blob  # noqa: E501
from ..models.capability import Capability  # noqa: E501
from ..models.data_element_choice import DataElementChoice  # noqa: E501
from ..models.data_type_def_xsd import DataTypeDefXsd  # noqa: E501
from ..models.direction import Direction  # noqa: E501
from ..models.embedded_data_specification import EmbeddedDataSpecification  # noqa: E501
from ..models.entity import Entity  # noqa: E501
from ..models.entity_type import EntityType  # noqa: E501
from ..models.extension import Extension  # noqa: E501
from ..models.file import File  # noqa: E501
from ..models.lang_string_name_type import LangStringNameType  # noqa: E501
from ..models.lang_string_text_type import LangStringTextType  # noqa: E501
from ..models.model_property import ModelProperty  # noqa: E501
from ..models.multi_language_property import MultiLanguageProperty  # noqa: E501
from ..models.operation import Operation  # noqa: E501
from ..models.operation_variable import OperationVariable  # noqa: E501
from ..models.qualifier import Qualifier  # noqa: E501
from ..models.range import Range  # noqa: E501
from ..models.reference import Reference  # noqa: E501
from ..models.reference_element import ReferenceElement  # noqa: E501
from ..models.relationship_element import RelationshipElement  # noqa: E501
from ..models.specific_asset_id import SpecificAssetId  # noqa: E501
from ..models.state_of_event import StateOfEvent  # noqa: E501
from ..models.submodel_element_collection import SubmodelElementCollection  # noqa: E501
from ..models.submodel_element_list import SubmodelElementList  # noqa: E501
import re  # noqa: E501

class SubmodelElementChoice(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, extensions=None, category=None, id_short=None, display_name=None, description=None, model_type=None, semantic_id=None, supplemental_semantic_ids=None, qualifiers=None, embedded_data_specifications=None, first=None, second=None, annotations=None, observed=None, direction=None, state=None, message_topic=None, message_broker=None, last_update=None, min_interval=None, max_interval=None, value=None, content_type=None, statements=None, entity_type=None, global_asset_id=None, specific_asset_ids=None, value_id=None, input_variables=None, output_variables=None, inoutput_variables=None, value_type=None, min=None, max=None, order_relevant=None, semantic_id_list_element=None, type_value_list_element=None, value_type_list_element=None):  # noqa: E501
        """SubmodelElementChoice - a model defined in OpenAPI

        :param extensions: The extensions of this SubmodelElementChoice.  # noqa: E501
        :type extensions: List[Extension]
        :param category: The category of this SubmodelElementChoice.  # noqa: E501
        :type category: str
        :param id_short: The id_short of this SubmodelElementChoice.  # noqa: E501
        :type id_short: object
        :param display_name: The display_name of this SubmodelElementChoice.  # noqa: E501
        :type display_name: List[LangStringNameType]
        :param description: The description of this SubmodelElementChoice.  # noqa: E501
        :type description: List[LangStringTextType]
        :param model_type: The model_type of this SubmodelElementChoice.  # noqa: E501
        :type model_type: str
        :param semantic_id: The semantic_id of this SubmodelElementChoice.  # noqa: E501
        :type semantic_id: Reference
        :param supplemental_semantic_ids: The supplemental_semantic_ids of this SubmodelElementChoice.  # noqa: E501
        :type supplemental_semantic_ids: List[Reference]
        :param qualifiers: The qualifiers of this SubmodelElementChoice.  # noqa: E501
        :type qualifiers: List[Qualifier]
        :param embedded_data_specifications: The embedded_data_specifications of this SubmodelElementChoice.  # noqa: E501
        :type embedded_data_specifications: List[EmbeddedDataSpecification]
        :param first: The first of this SubmodelElementChoice.  # noqa: E501
        :type first: Reference
        :param second: The second of this SubmodelElementChoice.  # noqa: E501
        :type second: Reference
        :param annotations: The annotations of this SubmodelElementChoice.  # noqa: E501
        :type annotations: List[DataElementChoice]
        :param observed: The observed of this SubmodelElementChoice.  # noqa: E501
        :type observed: Reference
        :param direction: The direction of this SubmodelElementChoice.  # noqa: E501
        :type direction: Direction
        :param state: The state of this SubmodelElementChoice.  # noqa: E501
        :type state: StateOfEvent
        :param message_topic: The message_topic of this SubmodelElementChoice.  # noqa: E501
        :type message_topic: str
        :param message_broker: The message_broker of this SubmodelElementChoice.  # noqa: E501
        :type message_broker: Reference
        :param last_update: The last_update of this SubmodelElementChoice.  # noqa: E501
        :type last_update: str
        :param min_interval: The min_interval of this SubmodelElementChoice.  # noqa: E501
        :type min_interval: str
        :param max_interval: The max_interval of this SubmodelElementChoice.  # noqa: E501
        :type max_interval: str
        :param value: The value of this SubmodelElementChoice.  # noqa: E501
        :type value: List[SubmodelElementChoice]
        :param content_type: The content_type of this SubmodelElementChoice.  # noqa: E501
        :type content_type: object
        :param statements: The statements of this SubmodelElementChoice.  # noqa: E501
        :type statements: List[SubmodelElementChoice]
        :param entity_type: The entity_type of this SubmodelElementChoice.  # noqa: E501
        :type entity_type: EntityType
        :param global_asset_id: The global_asset_id of this SubmodelElementChoice.  # noqa: E501
        :type global_asset_id: str
        :param specific_asset_ids: The specific_asset_ids of this SubmodelElementChoice.  # noqa: E501
        :type specific_asset_ids: List[SpecificAssetId]
        :param value_id: The value_id of this SubmodelElementChoice.  # noqa: E501
        :type value_id: Reference
        :param input_variables: The input_variables of this SubmodelElementChoice.  # noqa: E501
        :type input_variables: List[OperationVariable]
        :param output_variables: The output_variables of this SubmodelElementChoice.  # noqa: E501
        :type output_variables: List[OperationVariable]
        :param inoutput_variables: The inoutput_variables of this SubmodelElementChoice.  # noqa: E501
        :type inoutput_variables: List[OperationVariable]
        :param value_type: The value_type of this SubmodelElementChoice.  # noqa: E501
        :type value_type: DataTypeDefXsd
        :param min: The min of this SubmodelElementChoice.  # noqa: E501
        :type min: str
        :param max: The max of this SubmodelElementChoice.  # noqa: E501
        :type max: str
        :param order_relevant: The order_relevant of this SubmodelElementChoice.  # noqa: E501
        :type order_relevant: bool
        :param semantic_id_list_element: The semantic_id_list_element of this SubmodelElementChoice.  # noqa: E501
        :type semantic_id_list_element: Reference
        :param type_value_list_element: The type_value_list_element of this SubmodelElementChoice.  # noqa: E501
        :type type_value_list_element: AasSubmodelElements
        :param value_type_list_element: The value_type_list_element of this SubmodelElementChoice.  # noqa: E501
        :type value_type_list_element: DataTypeDefXsd
        """
        self.openapi_types = {
            'extensions': List[Extension],
            'category': str,
            'id_short': object,
            'display_name': List[LangStringNameType],
            'description': List[LangStringTextType],
            'model_type': str,
            'semantic_id': Reference,
            'supplemental_semantic_ids': List[Reference],
            'qualifiers': List[Qualifier],
            'embedded_data_specifications': List[EmbeddedDataSpecification],
            'first': Reference,
            'second': Reference,
            'annotations': List[DataElementChoice],
            'observed': Reference,
            'direction': Direction,
            'state': StateOfEvent,
            'message_topic': str,
            'message_broker': Reference,
            'last_update': str,
            'min_interval': str,
            'max_interval': str,
            'value': List[SubmodelElementChoice],
            'content_type': object,
            'statements': List[SubmodelElementChoice],
            'entity_type': EntityType,
            'global_asset_id': str,
            'specific_asset_ids': List[SpecificAssetId],
            'value_id': Reference,
            'input_variables': List[OperationVariable],
            'output_variables': List[OperationVariable],
            'inoutput_variables': List[OperationVariable],
            'value_type': DataTypeDefXsd,
            'min': str,
            'max': str,
            'order_relevant': bool,
            'semantic_id_list_element': Reference,
            'type_value_list_element': AasSubmodelElements,
            'value_type_list_element': DataTypeDefXsd
        }

        self.attribute_map = {
            'extensions': 'extensions',
            'category': 'category',
            'id_short': 'idShort',
            'display_name': 'displayName',
            'description': 'description',
            'model_type': 'modelType',
            'semantic_id': 'semanticId',
            'supplemental_semantic_ids': 'supplementalSemanticIds',
            'qualifiers': 'qualifiers',
            'embedded_data_specifications': 'embeddedDataSpecifications',
            'first': 'first',
            'second': 'second',
            'annotations': 'annotations',
            'observed': 'observed',
            'direction': 'direction',
            'state': 'state',
            'message_topic': 'messageTopic',
            'message_broker': 'messageBroker',
            'last_update': 'lastUpdate',
            'min_interval': 'minInterval',
            'max_interval': 'maxInterval',
            'value': 'value',
            'content_type': 'contentType',
            'statements': 'statements',
            'entity_type': 'entityType',
            'global_asset_id': 'globalAssetId',
            'specific_asset_ids': 'specificAssetIds',
            'value_id': 'valueId',
            'input_variables': 'inputVariables',
            'output_variables': 'outputVariables',
            'inoutput_variables': 'inoutputVariables',
            'value_type': 'valueType',
            'min': 'min',
            'max': 'max',
            'order_relevant': 'orderRelevant',
            'semantic_id_list_element': 'semanticIdListElement',
            'type_value_list_element': 'typeValueListElement',
            'value_type_list_element': 'valueTypeListElement'
        }

        self._extensions = extensions
        self._category = category
        self._id_short = id_short
        self._display_name = display_name
        self._description = description
        self._model_type = model_type
        self._semantic_id = semantic_id
        self._supplemental_semantic_ids = supplemental_semantic_ids
        self._qualifiers = qualifiers
        self._embedded_data_specifications = embedded_data_specifications
        self._first = first
        self._second = second
        self._annotations = annotations
        self._observed = observed
        self._direction = direction
        self._state = state
        self._message_topic = message_topic
        self._message_broker = message_broker
        self._last_update = last_update
        self._min_interval = min_interval
        self._max_interval = max_interval
        self._value = value
        self._content_type = content_type
        self._statements = statements
        self._entity_type = entity_type
        self._global_asset_id = global_asset_id
        self._specific_asset_ids = specific_asset_ids
        self._value_id = value_id
        self._input_variables = input_variables
        self._output_variables = output_variables
        self._inoutput_variables = inoutput_variables
        self._value_type = value_type
        self._min = min
        self._max = max
        self._order_relevant = order_relevant
        self._semantic_id_list_element = semantic_id_list_element
        self._type_value_list_element = type_value_list_element
        self._value_type_list_element = value_type_list_element

    @classmethod
    def from_dict(cls, dikt) -> 'SubmodelElementChoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubmodelElement_choice of this SubmodelElementChoice.  # noqa: E501
        :rtype: SubmodelElementChoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def extensions(self) -> List[Extension]:
        """Gets the extensions of this SubmodelElementChoice.


        :return: The extensions of this SubmodelElementChoice.
        :rtype: List[Extension]
        """
        return self._extensions

    @extensions.setter
    def extensions(self, extensions: List[Extension]):
        """Sets the extensions of this SubmodelElementChoice.


        :param extensions: The extensions of this SubmodelElementChoice.
        :type extensions: List[Extension]
        """
        if extensions is not None and len(extensions) < 1:
            raise ValueError("Invalid value for `extensions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._extensions = extensions

    @property
    def category(self) -> str:
        """Gets the category of this SubmodelElementChoice.


        :return: The category of this SubmodelElementChoice.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this SubmodelElementChoice.


        :param category: The category of this SubmodelElementChoice.
        :type category: str
        """
        if category is not None and len(category) > 128:
            raise ValueError("Invalid value for `category`, length must be less than or equal to `128`")  # noqa: E501
        if category is not None and len(category) < 1:
            raise ValueError("Invalid value for `category`, length must be greater than or equal to `1`")  # noqa: E501
        if category is not None and not re.search(r'^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$', category):  # noqa: E501
            raise ValueError("Invalid value for `category`, must be a follow pattern or equal to `/^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$/`")  # noqa: E501

        self._category = category

    @property
    def id_short(self) -> object:
        """Gets the id_short of this SubmodelElementChoice.


        :return: The id_short of this SubmodelElementChoice.
        :rtype: object
        """
        return self._id_short

    @id_short.setter
    def id_short(self, id_short: object):
        """Sets the id_short of this SubmodelElementChoice.


        :param id_short: The id_short of this SubmodelElementChoice.
        :type id_short: object
        """

        self._id_short = id_short

    @property
    def display_name(self) -> List[LangStringNameType]:
        """Gets the display_name of this SubmodelElementChoice.


        :return: The display_name of this SubmodelElementChoice.
        :rtype: List[LangStringNameType]
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: List[LangStringNameType]):
        """Sets the display_name of this SubmodelElementChoice.


        :param display_name: The display_name of this SubmodelElementChoice.
        :type display_name: List[LangStringNameType]
        """
        if display_name is not None and len(display_name) < 1:
            raise ValueError("Invalid value for `display_name`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self) -> List[LangStringTextType]:
        """Gets the description of this SubmodelElementChoice.


        :return: The description of this SubmodelElementChoice.
        :rtype: List[LangStringTextType]
        """
        return self._description

    @description.setter
    def description(self, description: List[LangStringTextType]):
        """Sets the description of this SubmodelElementChoice.


        :param description: The description of this SubmodelElementChoice.
        :type description: List[LangStringTextType]
        """
        if description is not None and len(description) < 1:
            raise ValueError("Invalid value for `description`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def model_type(self) -> str:
        """Gets the model_type of this SubmodelElementChoice.


        :return: The model_type of this SubmodelElementChoice.
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type: str):
        """Sets the model_type of this SubmodelElementChoice.


        :param model_type: The model_type of this SubmodelElementChoice.
        :type model_type: str
        """
        if model_type is None:
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501
        if model_type is not None and not re.search(r'SubmodelElementList', model_type):  # noqa: E501
            raise ValueError("Invalid value for `model_type`, must be a follow pattern or equal to `/SubmodelElementList/`")  # noqa: E501

        self._model_type = model_type

    @property
    def semantic_id(self) -> Reference:
        """Gets the semantic_id of this SubmodelElementChoice.


        :return: The semantic_id of this SubmodelElementChoice.
        :rtype: Reference
        """
        return self._semantic_id

    @semantic_id.setter
    def semantic_id(self, semantic_id: Reference):
        """Sets the semantic_id of this SubmodelElementChoice.


        :param semantic_id: The semantic_id of this SubmodelElementChoice.
        :type semantic_id: Reference
        """

        self._semantic_id = semantic_id

    @property
    def supplemental_semantic_ids(self) -> List[Reference]:
        """Gets the supplemental_semantic_ids of this SubmodelElementChoice.


        :return: The supplemental_semantic_ids of this SubmodelElementChoice.
        :rtype: List[Reference]
        """
        return self._supplemental_semantic_ids

    @supplemental_semantic_ids.setter
    def supplemental_semantic_ids(self, supplemental_semantic_ids: List[Reference]):
        """Sets the supplemental_semantic_ids of this SubmodelElementChoice.


        :param supplemental_semantic_ids: The supplemental_semantic_ids of this SubmodelElementChoice.
        :type supplemental_semantic_ids: List[Reference]
        """
        if supplemental_semantic_ids is not None and len(supplemental_semantic_ids) < 1:
            raise ValueError("Invalid value for `supplemental_semantic_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._supplemental_semantic_ids = supplemental_semantic_ids

    @property
    def qualifiers(self) -> List[Qualifier]:
        """Gets the qualifiers of this SubmodelElementChoice.


        :return: The qualifiers of this SubmodelElementChoice.
        :rtype: List[Qualifier]
        """
        return self._qualifiers

    @qualifiers.setter
    def qualifiers(self, qualifiers: List[Qualifier]):
        """Sets the qualifiers of this SubmodelElementChoice.


        :param qualifiers: The qualifiers of this SubmodelElementChoice.
        :type qualifiers: List[Qualifier]
        """
        if qualifiers is not None and len(qualifiers) < 1:
            raise ValueError("Invalid value for `qualifiers`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._qualifiers = qualifiers

    @property
    def embedded_data_specifications(self) -> List[EmbeddedDataSpecification]:
        """Gets the embedded_data_specifications of this SubmodelElementChoice.


        :return: The embedded_data_specifications of this SubmodelElementChoice.
        :rtype: List[EmbeddedDataSpecification]
        """
        return self._embedded_data_specifications

    @embedded_data_specifications.setter
    def embedded_data_specifications(self, embedded_data_specifications: List[EmbeddedDataSpecification]):
        """Sets the embedded_data_specifications of this SubmodelElementChoice.


        :param embedded_data_specifications: The embedded_data_specifications of this SubmodelElementChoice.
        :type embedded_data_specifications: List[EmbeddedDataSpecification]
        """
        if embedded_data_specifications is not None and len(embedded_data_specifications) < 1:
            raise ValueError("Invalid value for `embedded_data_specifications`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._embedded_data_specifications = embedded_data_specifications

    @property
    def first(self) -> Reference:
        """Gets the first of this SubmodelElementChoice.


        :return: The first of this SubmodelElementChoice.
        :rtype: Reference
        """
        return self._first

    @first.setter
    def first(self, first: Reference):
        """Sets the first of this SubmodelElementChoice.


        :param first: The first of this SubmodelElementChoice.
        :type first: Reference
        """
        if first is None:
            raise ValueError("Invalid value for `first`, must not be `None`")  # noqa: E501

        self._first = first

    @property
    def second(self) -> Reference:
        """Gets the second of this SubmodelElementChoice.


        :return: The second of this SubmodelElementChoice.
        :rtype: Reference
        """
        return self._second

    @second.setter
    def second(self, second: Reference):
        """Sets the second of this SubmodelElementChoice.


        :param second: The second of this SubmodelElementChoice.
        :type second: Reference
        """
        if second is None:
            raise ValueError("Invalid value for `second`, must not be `None`")  # noqa: E501

        self._second = second

    @property
    def annotations(self) -> List[DataElementChoice]:
        """Gets the annotations of this SubmodelElementChoice.


        :return: The annotations of this SubmodelElementChoice.
        :rtype: List[DataElementChoice]
        """
        return self._annotations

    @annotations.setter
    def annotations(self, annotations: List[DataElementChoice]):
        """Sets the annotations of this SubmodelElementChoice.


        :param annotations: The annotations of this SubmodelElementChoice.
        :type annotations: List[DataElementChoice]
        """
        if annotations is not None and len(annotations) < 1:
            raise ValueError("Invalid value for `annotations`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._annotations = annotations

    @property
    def observed(self) -> Reference:
        """Gets the observed of this SubmodelElementChoice.


        :return: The observed of this SubmodelElementChoice.
        :rtype: Reference
        """
        return self._observed

    @observed.setter
    def observed(self, observed: Reference):
        """Sets the observed of this SubmodelElementChoice.


        :param observed: The observed of this SubmodelElementChoice.
        :type observed: Reference
        """
        if observed is None:
            raise ValueError("Invalid value for `observed`, must not be `None`")  # noqa: E501

        self._observed = observed

    @property
    def direction(self) -> Direction:
        """Gets the direction of this SubmodelElementChoice.


        :return: The direction of this SubmodelElementChoice.
        :rtype: Direction
        """
        return self._direction

    @direction.setter
    def direction(self, direction: Direction):
        """Sets the direction of this SubmodelElementChoice.


        :param direction: The direction of this SubmodelElementChoice.
        :type direction: Direction
        """
        if direction is None:
            raise ValueError("Invalid value for `direction`, must not be `None`")  # noqa: E501

        self._direction = direction

    @property
    def state(self) -> StateOfEvent:
        """Gets the state of this SubmodelElementChoice.


        :return: The state of this SubmodelElementChoice.
        :rtype: StateOfEvent
        """
        return self._state

    @state.setter
    def state(self, state: StateOfEvent):
        """Sets the state of this SubmodelElementChoice.


        :param state: The state of this SubmodelElementChoice.
        :type state: StateOfEvent
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def message_topic(self) -> str:
        """Gets the message_topic of this SubmodelElementChoice.


        :return: The message_topic of this SubmodelElementChoice.
        :rtype: str
        """
        return self._message_topic

    @message_topic.setter
    def message_topic(self, message_topic: str):
        """Sets the message_topic of this SubmodelElementChoice.


        :param message_topic: The message_topic of this SubmodelElementChoice.
        :type message_topic: str
        """
        if message_topic is not None and len(message_topic) > 255:
            raise ValueError("Invalid value for `message_topic`, length must be less than or equal to `255`")  # noqa: E501
        if message_topic is not None and len(message_topic) < 1:
            raise ValueError("Invalid value for `message_topic`, length must be greater than or equal to `1`")  # noqa: E501
        if message_topic is not None and not re.search(r'^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$', message_topic):  # noqa: E501
            raise ValueError("Invalid value for `message_topic`, must be a follow pattern or equal to `/^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$/`")  # noqa: E501

        self._message_topic = message_topic

    @property
    def message_broker(self) -> Reference:
        """Gets the message_broker of this SubmodelElementChoice.


        :return: The message_broker of this SubmodelElementChoice.
        :rtype: Reference
        """
        return self._message_broker

    @message_broker.setter
    def message_broker(self, message_broker: Reference):
        """Sets the message_broker of this SubmodelElementChoice.


        :param message_broker: The message_broker of this SubmodelElementChoice.
        :type message_broker: Reference
        """

        self._message_broker = message_broker

    @property
    def last_update(self) -> str:
        """Gets the last_update of this SubmodelElementChoice.


        :return: The last_update of this SubmodelElementChoice.
        :rtype: str
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update: str):
        """Sets the last_update of this SubmodelElementChoice.


        :param last_update: The last_update of this SubmodelElementChoice.
        :type last_update: str
        """
        if last_update is not None and not re.search(r'^-?(([1-9][0-9][0-9][0-9]+)|(0[0-9][0-9][0-9]))-((0[1-9])|(1[0-2]))-((0[1-9])|([12][0-9])|(3[01]))T(((([01][0-9])|(2[0-3])):[0-5][0-9]:([0-5][0-9])(\.[0-9]+)?)|24:00:00(\.0+)?)(Z|\+00:00|-00:00)$', last_update):  # noqa: E501
            raise ValueError("Invalid value for `last_update`, must be a follow pattern or equal to `/^-?(([1-9][0-9][0-9][0-9]+)|(0[0-9][0-9][0-9]))-((0[1-9])|(1[0-2]))-((0[1-9])|([12][0-9])|(3[01]))T(((([01][0-9])|(2[0-3])):[0-5][0-9]:([0-5][0-9])(\.[0-9]+)?)|24:00:00(\.0+)?)(Z|\+00:00|-00:00)$/`")  # noqa: E501

        self._last_update = last_update

    @property
    def min_interval(self) -> str:
        """Gets the min_interval of this SubmodelElementChoice.


        :return: The min_interval of this SubmodelElementChoice.
        :rtype: str
        """
        return self._min_interval

    @min_interval.setter
    def min_interval(self, min_interval: str):
        """Sets the min_interval of this SubmodelElementChoice.


        :param min_interval: The min_interval of this SubmodelElementChoice.
        :type min_interval: str
        """
        if min_interval is not None and not re.search(r'^-?P((([0-9]+Y([0-9]+M)?([0-9]+D)?|([0-9]+M)([0-9]+D)?|([0-9]+D))(T(([0-9]+H)([0-9]+M)?([0-9]+(\.[0-9]+)?S)?|([0-9]+M)([0-9]+(\.[0-9]+)?S)?|([0-9]+(\.[0-9]+)?S)))?)|(T(([0-9]+H)([0-9]+M)?([0-9]+(\.[0-9]+)?S)?|([0-9]+M)([0-9]+(\.[0-9]+)?S)?|([0-9]+(\.[0-9]+)?S))))$', min_interval):  # noqa: E501
            raise ValueError("Invalid value for `min_interval`, must be a follow pattern or equal to `/^-?P((([0-9]+Y([0-9]+M)?([0-9]+D)?|([0-9]+M)([0-9]+D)?|([0-9]+D))(T(([0-9]+H)([0-9]+M)?([0-9]+(\.[0-9]+)?S)?|([0-9]+M)([0-9]+(\.[0-9]+)?S)?|([0-9]+(\.[0-9]+)?S)))?)|(T(([0-9]+H)([0-9]+M)?([0-9]+(\.[0-9]+)?S)?|([0-9]+M)([0-9]+(\.[0-9]+)?S)?|([0-9]+(\.[0-9]+)?S))))$/`")  # noqa: E501

        self._min_interval = min_interval

    @property
    def max_interval(self) -> str:
        """Gets the max_interval of this SubmodelElementChoice.


        :return: The max_interval of this SubmodelElementChoice.
        :rtype: str
        """
        return self._max_interval

    @max_interval.setter
    def max_interval(self, max_interval: str):
        """Sets the max_interval of this SubmodelElementChoice.


        :param max_interval: The max_interval of this SubmodelElementChoice.
        :type max_interval: str
        """
        if max_interval is not None and not re.search(r'^-?P((([0-9]+Y([0-9]+M)?([0-9]+D)?|([0-9]+M)([0-9]+D)?|([0-9]+D))(T(([0-9]+H)([0-9]+M)?([0-9]+(\.[0-9]+)?S)?|([0-9]+M)([0-9]+(\.[0-9]+)?S)?|([0-9]+(\.[0-9]+)?S)))?)|(T(([0-9]+H)([0-9]+M)?([0-9]+(\.[0-9]+)?S)?|([0-9]+M)([0-9]+(\.[0-9]+)?S)?|([0-9]+(\.[0-9]+)?S))))$', max_interval):  # noqa: E501
            raise ValueError("Invalid value for `max_interval`, must be a follow pattern or equal to `/^-?P((([0-9]+Y([0-9]+M)?([0-9]+D)?|([0-9]+M)([0-9]+D)?|([0-9]+D))(T(([0-9]+H)([0-9]+M)?([0-9]+(\.[0-9]+)?S)?|([0-9]+M)([0-9]+(\.[0-9]+)?S)?|([0-9]+(\.[0-9]+)?S)))?)|(T(([0-9]+H)([0-9]+M)?([0-9]+(\.[0-9]+)?S)?|([0-9]+M)([0-9]+(\.[0-9]+)?S)?|([0-9]+(\.[0-9]+)?S))))$/`")  # noqa: E501

        self._max_interval = max_interval

    @property
    def value(self) -> List[SubmodelElementChoice]:
        """Gets the value of this SubmodelElementChoice.


        :return: The value of this SubmodelElementChoice.
        :rtype: List[SubmodelElementChoice]
        """
        return self._value

    @value.setter
    def value(self, value: List[SubmodelElementChoice]):
        """Sets the value of this SubmodelElementChoice.


        :param value: The value of this SubmodelElementChoice.
        :type value: List[SubmodelElementChoice]
        """
        if value is not None and len(value) < 1:
            raise ValueError("Invalid value for `value`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._value = value

    @property
    def content_type(self) -> object:
        """Gets the content_type of this SubmodelElementChoice.


        :return: The content_type of this SubmodelElementChoice.
        :rtype: object
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type: object):
        """Sets the content_type of this SubmodelElementChoice.


        :param content_type: The content_type of this SubmodelElementChoice.
        :type content_type: object
        """
        if content_type is None:
            raise ValueError("Invalid value for `content_type`, must not be `None`")  # noqa: E501

        self._content_type = content_type

    @property
    def statements(self) -> List[SubmodelElementChoice]:
        """Gets the statements of this SubmodelElementChoice.


        :return: The statements of this SubmodelElementChoice.
        :rtype: List[SubmodelElementChoice]
        """
        return self._statements

    @statements.setter
    def statements(self, statements: List[SubmodelElementChoice]):
        """Sets the statements of this SubmodelElementChoice.


        :param statements: The statements of this SubmodelElementChoice.
        :type statements: List[SubmodelElementChoice]
        """
        if statements is not None and len(statements) < 1:
            raise ValueError("Invalid value for `statements`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._statements = statements

    @property
    def entity_type(self) -> EntityType:
        """Gets the entity_type of this SubmodelElementChoice.


        :return: The entity_type of this SubmodelElementChoice.
        :rtype: EntityType
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type: EntityType):
        """Sets the entity_type of this SubmodelElementChoice.


        :param entity_type: The entity_type of this SubmodelElementChoice.
        :type entity_type: EntityType
        """
        if entity_type is None:
            raise ValueError("Invalid value for `entity_type`, must not be `None`")  # noqa: E501

        self._entity_type = entity_type

    @property
    def global_asset_id(self) -> str:
        """Gets the global_asset_id of this SubmodelElementChoice.


        :return: The global_asset_id of this SubmodelElementChoice.
        :rtype: str
        """
        return self._global_asset_id

    @global_asset_id.setter
    def global_asset_id(self, global_asset_id: str):
        """Sets the global_asset_id of this SubmodelElementChoice.


        :param global_asset_id: The global_asset_id of this SubmodelElementChoice.
        :type global_asset_id: str
        """
        if global_asset_id is not None and len(global_asset_id) > 2000:
            raise ValueError("Invalid value for `global_asset_id`, length must be less than or equal to `2000`")  # noqa: E501
        if global_asset_id is not None and len(global_asset_id) < 1:
            raise ValueError("Invalid value for `global_asset_id`, length must be greater than or equal to `1`")  # noqa: E501
        if global_asset_id is not None and not re.search(r'^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$', global_asset_id):  # noqa: E501
            raise ValueError("Invalid value for `global_asset_id`, must be a follow pattern or equal to `/^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$/`")  # noqa: E501

        self._global_asset_id = global_asset_id

    @property
    def specific_asset_ids(self) -> List[SpecificAssetId]:
        """Gets the specific_asset_ids of this SubmodelElementChoice.


        :return: The specific_asset_ids of this SubmodelElementChoice.
        :rtype: List[SpecificAssetId]
        """
        return self._specific_asset_ids

    @specific_asset_ids.setter
    def specific_asset_ids(self, specific_asset_ids: List[SpecificAssetId]):
        """Sets the specific_asset_ids of this SubmodelElementChoice.


        :param specific_asset_ids: The specific_asset_ids of this SubmodelElementChoice.
        :type specific_asset_ids: List[SpecificAssetId]
        """
        if specific_asset_ids is not None and len(specific_asset_ids) < 1:
            raise ValueError("Invalid value for `specific_asset_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._specific_asset_ids = specific_asset_ids

    @property
    def value_id(self) -> Reference:
        """Gets the value_id of this SubmodelElementChoice.


        :return: The value_id of this SubmodelElementChoice.
        :rtype: Reference
        """
        return self._value_id

    @value_id.setter
    def value_id(self, value_id: Reference):
        """Sets the value_id of this SubmodelElementChoice.


        :param value_id: The value_id of this SubmodelElementChoice.
        :type value_id: Reference
        """

        self._value_id = value_id

    @property
    def input_variables(self) -> List[OperationVariable]:
        """Gets the input_variables of this SubmodelElementChoice.


        :return: The input_variables of this SubmodelElementChoice.
        :rtype: List[OperationVariable]
        """
        return self._input_variables

    @input_variables.setter
    def input_variables(self, input_variables: List[OperationVariable]):
        """Sets the input_variables of this SubmodelElementChoice.


        :param input_variables: The input_variables of this SubmodelElementChoice.
        :type input_variables: List[OperationVariable]
        """
        if input_variables is not None and len(input_variables) < 1:
            raise ValueError("Invalid value for `input_variables`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._input_variables = input_variables

    @property
    def output_variables(self) -> List[OperationVariable]:
        """Gets the output_variables of this SubmodelElementChoice.


        :return: The output_variables of this SubmodelElementChoice.
        :rtype: List[OperationVariable]
        """
        return self._output_variables

    @output_variables.setter
    def output_variables(self, output_variables: List[OperationVariable]):
        """Sets the output_variables of this SubmodelElementChoice.


        :param output_variables: The output_variables of this SubmodelElementChoice.
        :type output_variables: List[OperationVariable]
        """
        if output_variables is not None and len(output_variables) < 1:
            raise ValueError("Invalid value for `output_variables`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._output_variables = output_variables

    @property
    def inoutput_variables(self) -> List[OperationVariable]:
        """Gets the inoutput_variables of this SubmodelElementChoice.


        :return: The inoutput_variables of this SubmodelElementChoice.
        :rtype: List[OperationVariable]
        """
        return self._inoutput_variables

    @inoutput_variables.setter
    def inoutput_variables(self, inoutput_variables: List[OperationVariable]):
        """Sets the inoutput_variables of this SubmodelElementChoice.


        :param inoutput_variables: The inoutput_variables of this SubmodelElementChoice.
        :type inoutput_variables: List[OperationVariable]
        """
        if inoutput_variables is not None and len(inoutput_variables) < 1:
            raise ValueError("Invalid value for `inoutput_variables`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._inoutput_variables = inoutput_variables

    @property
    def value_type(self) -> DataTypeDefXsd:
        """Gets the value_type of this SubmodelElementChoice.


        :return: The value_type of this SubmodelElementChoice.
        :rtype: DataTypeDefXsd
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type: DataTypeDefXsd):
        """Sets the value_type of this SubmodelElementChoice.


        :param value_type: The value_type of this SubmodelElementChoice.
        :type value_type: DataTypeDefXsd
        """
        if value_type is None:
            raise ValueError("Invalid value for `value_type`, must not be `None`")  # noqa: E501

        self._value_type = value_type

    @property
    def min(self) -> str:
        """Gets the min of this SubmodelElementChoice.


        :return: The min of this SubmodelElementChoice.
        :rtype: str
        """
        return self._min

    @min.setter
    def min(self, min: str):
        """Sets the min of this SubmodelElementChoice.


        :param min: The min of this SubmodelElementChoice.
        :type min: str
        """

        self._min = min

    @property
    def max(self) -> str:
        """Gets the max of this SubmodelElementChoice.


        :return: The max of this SubmodelElementChoice.
        :rtype: str
        """
        return self._max

    @max.setter
    def max(self, max: str):
        """Sets the max of this SubmodelElementChoice.


        :param max: The max of this SubmodelElementChoice.
        :type max: str
        """

        self._max = max

    @property
    def order_relevant(self) -> bool:
        """Gets the order_relevant of this SubmodelElementChoice.


        :return: The order_relevant of this SubmodelElementChoice.
        :rtype: bool
        """
        return self._order_relevant

    @order_relevant.setter
    def order_relevant(self, order_relevant: bool):
        """Sets the order_relevant of this SubmodelElementChoice.


        :param order_relevant: The order_relevant of this SubmodelElementChoice.
        :type order_relevant: bool
        """

        self._order_relevant = order_relevant

    @property
    def semantic_id_list_element(self) -> Reference:
        """Gets the semantic_id_list_element of this SubmodelElementChoice.


        :return: The semantic_id_list_element of this SubmodelElementChoice.
        :rtype: Reference
        """
        return self._semantic_id_list_element

    @semantic_id_list_element.setter
    def semantic_id_list_element(self, semantic_id_list_element: Reference):
        """Sets the semantic_id_list_element of this SubmodelElementChoice.


        :param semantic_id_list_element: The semantic_id_list_element of this SubmodelElementChoice.
        :type semantic_id_list_element: Reference
        """

        self._semantic_id_list_element = semantic_id_list_element

    @property
    def type_value_list_element(self) -> AasSubmodelElements:
        """Gets the type_value_list_element of this SubmodelElementChoice.


        :return: The type_value_list_element of this SubmodelElementChoice.
        :rtype: AasSubmodelElements
        """
        return self._type_value_list_element

    @type_value_list_element.setter
    def type_value_list_element(self, type_value_list_element: AasSubmodelElements):
        """Sets the type_value_list_element of this SubmodelElementChoice.


        :param type_value_list_element: The type_value_list_element of this SubmodelElementChoice.
        :type type_value_list_element: AasSubmodelElements
        """
        if type_value_list_element is None:
            raise ValueError("Invalid value for `type_value_list_element`, must not be `None`")  # noqa: E501

        self._type_value_list_element = type_value_list_element

    @property
    def value_type_list_element(self) -> DataTypeDefXsd:
        """Gets the value_type_list_element of this SubmodelElementChoice.


        :return: The value_type_list_element of this SubmodelElementChoice.
        :rtype: DataTypeDefXsd
        """
        return self._value_type_list_element

    @value_type_list_element.setter
    def value_type_list_element(self, value_type_list_element: DataTypeDefXsd):
        """Sets the value_type_list_element of this SubmodelElementChoice.


        :param value_type_list_element: The value_type_list_element of this SubmodelElementChoice.
        :type value_type_list_element: DataTypeDefXsd
        """

        self._value_type_list_element = value_type_list_element
