from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DataTypeIec61360(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BLOB = 'BLOB'
    BOOLEAN = 'BOOLEAN'
    DATE = 'DATE'
    FILE = 'FILE'
    HTML = 'HTML'
    INTEGER_COUNT = 'INTEGER_COUNT'
    INTEGER_CURRENCY = 'INTEGER_CURRENCY'
    INTEGER_MEASURE = 'INTEGER_MEASURE'
    IRDI = 'IRDI'
    IRI = 'IRI'
    RATIONAL = 'RATIONAL'
    RATIONAL_MEASURE = 'RATIONAL_MEASURE'
    REAL_COUNT = 'REAL_COUNT'
    REAL_CURRENCY = 'REAL_CURRENCY'
    REAL_MEASURE = 'REAL_MEASURE'
    STRING = 'STRING'
    STRING_TRANSLATABLE = 'STRING_TRANSLATABLE'
    TIME = 'TIME'
    TIMESTAMP = 'TIMESTAMP'
    def __init__(self):  # noqa: E501
        """DataTypeIec61360 - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DataTypeIec61360':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataTypeIec61360 of this DataTypeIec61360.  # noqa: E501
        :rtype: DataTypeIec61360
        """
        return util.deserialize_model(dikt, cls)
