from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.administrative_information import AdministrativeInformation
from openapi_server.models.extension import Extension
from openapi_server.models.lang_string_name_type import LangStringNameType
from openapi_server.models.lang_string_text_type import LangStringTextType
from openapi_server.models.model_type import ModelType
import re
from openapi_server import util

from openapi_server.models.administrative_information import AdministrativeInformation  # noqa: E501
from openapi_server.models.extension import Extension  # noqa: E501
from openapi_server.models.lang_string_name_type import LangStringNameType  # noqa: E501
from openapi_server.models.lang_string_text_type import LangStringTextType  # noqa: E501
from openapi_server.models.model_type import ModelType  # noqa: E501
import re  # noqa: E501

class Identifiable(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, extensions=None, category=None, id_short=None, display_name=None, description=None, model_type=None, administration=None, id=None):  # noqa: E501
        """Identifiable - a model defined in OpenAPI

        :param extensions: The extensions of this Identifiable.  # noqa: E501
        :type extensions: List[Extension]
        :param category: The category of this Identifiable.  # noqa: E501
        :type category: str
        :param id_short: The id_short of this Identifiable.  # noqa: E501
        :type id_short: object
        :param display_name: The display_name of this Identifiable.  # noqa: E501
        :type display_name: List[LangStringNameType]
        :param description: The description of this Identifiable.  # noqa: E501
        :type description: List[LangStringTextType]
        :param model_type: The model_type of this Identifiable.  # noqa: E501
        :type model_type: ModelType
        :param administration: The administration of this Identifiable.  # noqa: E501
        :type administration: AdministrativeInformation
        :param id: The id of this Identifiable.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {
            'extensions': List[Extension],
            'category': str,
            'id_short': object,
            'display_name': List[LangStringNameType],
            'description': List[LangStringTextType],
            'model_type': ModelType,
            'administration': AdministrativeInformation,
            'id': str
        }

        self.attribute_map = {
            'extensions': 'extensions',
            'category': 'category',
            'id_short': 'idShort',
            'display_name': 'displayName',
            'description': 'description',
            'model_type': 'modelType',
            'administration': 'administration',
            'id': 'id'
        }

        self._extensions = extensions
        self._category = category
        self._id_short = id_short
        self._display_name = display_name
        self._description = description
        self._model_type = model_type
        self._administration = administration
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'Identifiable':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Identifiable of this Identifiable.  # noqa: E501
        :rtype: Identifiable
        """
        return util.deserialize_model(dikt, cls)

    @property
    def extensions(self) -> List[Extension]:
        """Gets the extensions of this Identifiable.


        :return: The extensions of this Identifiable.
        :rtype: List[Extension]
        """
        return self._extensions

    @extensions.setter
    def extensions(self, extensions: List[Extension]):
        """Sets the extensions of this Identifiable.


        :param extensions: The extensions of this Identifiable.
        :type extensions: List[Extension]
        """
        if extensions is not None and len(extensions) < 1:
            raise ValueError("Invalid value for `extensions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._extensions = extensions

    @property
    def category(self) -> str:
        """Gets the category of this Identifiable.


        :return: The category of this Identifiable.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this Identifiable.


        :param category: The category of this Identifiable.
        :type category: str
        """
        if category is not None and len(category) > 128:
            raise ValueError("Invalid value for `category`, length must be less than or equal to `128`")  # noqa: E501
        if category is not None and len(category) < 1:
            raise ValueError("Invalid value for `category`, length must be greater than or equal to `1`")  # noqa: E501
        if category is not None and not re.search(r'^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$', category):  # noqa: E501
            raise ValueError("Invalid value for `category`, must be a follow pattern or equal to `/^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$/`")  # noqa: E501

        self._category = category

    @property
    def id_short(self) -> object:
        """Gets the id_short of this Identifiable.


        :return: The id_short of this Identifiable.
        :rtype: object
        """
        return self._id_short

    @id_short.setter
    def id_short(self, id_short: object):
        """Sets the id_short of this Identifiable.


        :param id_short: The id_short of this Identifiable.
        :type id_short: object
        """

        self._id_short = id_short

    @property
    def display_name(self) -> List[LangStringNameType]:
        """Gets the display_name of this Identifiable.


        :return: The display_name of this Identifiable.
        :rtype: List[LangStringNameType]
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: List[LangStringNameType]):
        """Sets the display_name of this Identifiable.


        :param display_name: The display_name of this Identifiable.
        :type display_name: List[LangStringNameType]
        """
        if display_name is not None and len(display_name) < 1:
            raise ValueError("Invalid value for `display_name`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self) -> List[LangStringTextType]:
        """Gets the description of this Identifiable.


        :return: The description of this Identifiable.
        :rtype: List[LangStringTextType]
        """
        return self._description

    @description.setter
    def description(self, description: List[LangStringTextType]):
        """Sets the description of this Identifiable.


        :param description: The description of this Identifiable.
        :type description: List[LangStringTextType]
        """
        if description is not None and len(description) < 1:
            raise ValueError("Invalid value for `description`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def model_type(self) -> ModelType:
        """Gets the model_type of this Identifiable.


        :return: The model_type of this Identifiable.
        :rtype: ModelType
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type: ModelType):
        """Sets the model_type of this Identifiable.


        :param model_type: The model_type of this Identifiable.
        :type model_type: ModelType
        """
        if model_type is None:
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501

        self._model_type = model_type

    @property
    def administration(self) -> AdministrativeInformation:
        """Gets the administration of this Identifiable.


        :return: The administration of this Identifiable.
        :rtype: AdministrativeInformation
        """
        return self._administration

    @administration.setter
    def administration(self, administration: AdministrativeInformation):
        """Sets the administration of this Identifiable.


        :param administration: The administration of this Identifiable.
        :type administration: AdministrativeInformation
        """

        self._administration = administration

    @property
    def id(self) -> str:
        """Gets the id of this Identifiable.


        :return: The id of this Identifiable.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Identifiable.


        :param id: The id of this Identifiable.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) > 2000:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `2000`")  # noqa: E501
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")  # noqa: E501
        if id is not None and not re.search(r'^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$', id):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/^([\t\n\r -퟿-�]|\ud800[\udc00-\udfff]|[\ud801-\udbfe][\udc00-\udfff]|\udbff[\udc00-\udfff])*$/`")  # noqa: E501

        self._id = id
