from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ModelType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ANNOTATEDRELATIONSHIPELEMENT = 'AnnotatedRelationshipElement'
    ASSETADMINISTRATIONSHELL = 'AssetAdministrationShell'
    BASICEVENTELEMENT = 'BasicEventElement'
    BLOB = 'Blob'
    CAPABILITY = 'Capability'
    CONCEPTDESCRIPTION = 'ConceptDescription'
    DATASPECIFICATIONIEC61360 = 'DataSpecificationIec61360'
    ENTITY = 'Entity'
    FILE = 'File'
    MULTILANGUAGEPROPERTY = 'MultiLanguageProperty'
    OPERATION = 'Operation'
    PROPERTY = 'Property'
    RANGE = 'Range'
    REFERENCEELEMENT = 'ReferenceElement'
    RELATIONSHIPELEMENT = 'RelationshipElement'
    SUBMODEL = 'Submodel'
    SUBMODELELEMENTCOLLECTION = 'SubmodelElementCollection'
    SUBMODELELEMENTLIST = 'SubmodelElementList'
    def __init__(self):  # noqa: E501
        """ModelType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ModelType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelType of this ModelType.  # noqa: E501
        :rtype: ModelType
        """
        return util.deserialize_model(dikt, cls)
