from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.key import Key
from openapi_server.models.reference_types import ReferenceTypes
from openapi_server import util

from openapi_server.models.key import Key  # noqa: E501
from openapi_server.models.reference_types import ReferenceTypes  # noqa: E501

class ReferenceElementValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, keys=None):  # noqa: E501
        """ReferenceElementValue - a model defined in OpenAPI

        :param type: The type of this ReferenceElementValue.  # noqa: E501
        :type type: ReferenceTypes
        :param keys: The keys of this ReferenceElementValue.  # noqa: E501
        :type keys: List[Key]
        """
        self.openapi_types = {
            'type': ReferenceTypes,
            'keys': List[Key]
        }

        self.attribute_map = {
            'type': 'type',
            'keys': 'keys'
        }

        self._type = type
        self._keys = keys

    @classmethod
    def from_dict(cls, dikt) -> 'ReferenceElementValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReferenceElementValue of this ReferenceElementValue.  # noqa: E501
        :rtype: ReferenceElementValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> ReferenceTypes:
        """Gets the type of this ReferenceElementValue.


        :return: The type of this ReferenceElementValue.
        :rtype: ReferenceTypes
        """
        return self._type

    @type.setter
    def type(self, type: ReferenceTypes):
        """Sets the type of this ReferenceElementValue.


        :param type: The type of this ReferenceElementValue.
        :type type: ReferenceTypes
        """

        self._type = type

    @property
    def keys(self) -> List[Key]:
        """Gets the keys of this ReferenceElementValue.


        :return: The keys of this ReferenceElementValue.
        :rtype: List[Key]
        """
        return self._keys

    @keys.setter
    def keys(self, keys: List[Key]):
        """Sets the keys of this ReferenceElementValue.


        :param keys: The keys of this ReferenceElementValue.
        :type keys: List[Key]
        """

        self._keys = keys
